### ISSUE TITLE
Support for deleted files when recreating them

### ISSUE THREAD

**Issue by prochri** [kevinhwang91/nvim-fundo#11]
Very usefull plugin!

I have the following scenario: I accidentally delete a file and want to restore it's contents and history by creating it agian in neovim and going back in the history. This does not work at the moment.

A workaround is to create the file outside of neovim and then open it again, resulting in the complete history being loaded.

What would it take to implement this? I would be up to implementing it myself and submitting a PR.

**Comment by kevinhwang91** [comment]
I think scanning the archives directory per hour is enough for your delete accident.
