### ISSUE TITLE
`Log/Graph` view? from demo

### ISSUE THREAD

**Issue by NormTurtle** [kevinhwang91/nvim-fundo#3]
how to i get the left-sided view ???

as this view 
![image](https://github.com/kevinhwang91/nvim-fundo/assets/108952834/ffecab2f-e01f-4100-86bf-409334dbb8a9)

**Comment by adamency** [comment]
Yes @kevinhwang91, can you please provide the plugin you're using (I guess it's external, cause it's not documented in your project) ?

**Comment by kevinhwang91** [comment]
https://github.com/mbbill/undotree

**Comment by NormTurtle** [comment]
@kevinhwang91 please share you config
