### ISSUE TITLE
Can Fundo restore an undofile without any archive for the file ?

### ISSUE THREAD

**Issue by adamency** [kevinhwang91/nvim-fundo#4]
First of all thanks a whole lot for this plugin which I starred right away as this is my biggest wish to have this in `(n)vim` !

I'm asking this because it is technically possible (though forbidden by the C implementation for undo in both `vim` and `nvim`) to load the undofile by itself on an empty file in order to restore its content with "geneally" good results, all the more if the history was stored since the beginning.

See:
- https://groups.google.com/g/vim_use/c/pOia0eB8ZWo/m/FmIQ4lUOPDIJ
- https://github.com/chrisbra/vim-mq-patches/blob/master/undorecover

However your readme seems to indicate that those archive files are necessary, and thus `fundo` can only work on content edited **after** installing the plugin. Am I correct ?

**Comment by kevinhwang91** [comment]
No,  need a new command like `undorecovery` you mention above.

> However your readme seems to indicate that those archive files are necessary, and thus fundo can only work on content edited after installing the plugin. Am I correct ?

Yes.
