### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by MichaelC001** [kevinhwang91/nvim-fundo#5]
![CleanShot_2023_12_17_141900](https://github.com/kevinhwang91/nvim-fundo/assets/90915827/07aa2df5-0bf7-4a52-a4e9-083ac6d85457)
config this plugin with lazy.nvim
but press u will not undo when the file changed outside

**Comment by kevinhwang91** [comment]
I don't use lazy.nvim￼

**Comment by serranomorante** [comment]
I use lazy.nvim and pressing `u` to undo external changes do work. From your screenshot I can see you're using `run = ...` when you should be using `build = ...`

Here's my lazy.nvim config for nvim-fundo.

```lua
return {
  "kevinhwang91/nvim-fundo",
  dependencies = {
    "kevinhwang91/promise-async",
  },
  build = function() require("fundo").install() end,
  lazy = false,
  init = function() vim.opt.undofile = true end,
  config = true,
}
```

**Comment by tan-wei** [comment]
@serranomorante `config = true` is error. You should use
```lu`
config = function()
    require("fundo").setup()
end
```
