### ISSUE TITLE
[question] trying to understand how nvim-fundo works

### ISSUE THREAD

**Issue by serranomorante** [kevinhwang91/nvim-fundo#6]
Thanks a lot for this plugin!

I recently experienced a crash trying to view my undo tree (with another plugin). The crash was due to a corrupted undo file. I deleted the file (from my `undodir` directory) and it fixed the problem. I still don't know the root of the cause and it doesn't matter that much.

But I wanted to ask, how does this plugin works and integrates with neovim?

I can see that I now have 2 directories that stores undo files:
1. my `undodir` directory (`.cache/nvim/undodir`)
2. the `nvim-fundo` directory (`.cache/nvim/fundo`)

Both directories seem to be storing the "same" undo files.

Is not clear from the README what can be the side effects of this (if there's any). I mean, how does neovim knows which undo file from which directory should it pick (`undodir` or `fundo`) to make an undo after I press `u`? Is there any kind of merging involve between the two files?

Thank you in advance for helping me to fill this gap.

**Comment by kevinhwang91** [comment]
> I can see that I now have 2 directories that stores undo files:

No, `undodir` stores the undo files by default. `fundo` stores the latest file saved inside Neovim which can match the undo data stored under `undodir` dir.

Ask your title question.
1. fundo store the latest file if you save buffer in Neovim under `fundo` dir.
2. fundo checks whether the current buffer (call it A) can read undo information in `BufReadPost` event, if not, read the file stored under `fundo` dir to buffer, now the buffer content can match the undo information. Read back the A content, now the undo information is valid.

fundo never hack `u` action.
