### ISSUE TITLE
Enabling `nvim-fundo` is causing the file "last location mark" to be lost

### ISSUE THREAD

**Issue by farzadmf** [kevinhwang91/nvim-fundo#7]
Hi, I've been using your plugin since the beginning of time 😆 , and I've been pretty happy with it.

But, just recently, I noticed an issue where it causes my "last-location mark" for a file to be lost. It could very well be some plugin conflict (I have QUITE A FEW plugins), but seems like the issue is gone if I disable `nvim-fundo`.

Just to clarify: I have an `autocmd` that uses `vim.api.nvim_buf_get_mark(0, '"')` to get the mark and restore it, but seems like just recently, that call is returning `{0 , 0}` if I enable `nvim-fundo`.

**Comment by kevinhwang91** [comment]
Please provide the reproduced script.

**Comment by farzadmf** [comment]
Well, that's a tough one 😛, since, as I mentioned, I have QUITE a few plugins. I'll try to see if I can create something, but in the meanwhile, do you by any chance have an idea what could be causing this issue?

**Comment by kevinhwang91** [comment]
Check out `shada` .

**Comment by farzadmf** [comment]
Wierdly enought, seems like it was happening at some point, and now it's not happening anymore. Not sure if it's because I updated something to fix the issue.

But yeah, the issue seems to be resolved (by itself) [for now].
