### ISSUE TITLE
This is not work on my arch linux

### ISSUE THREAD

**Issue by Nestos0** [kevinhwang91/nvim-fundo#8]
```lua
    {
        "kevinhwang91/nvim-fundo",
        dependencies = {
            "kevinhwang91/promise-async",
        },
        build = function() require("fundo").install() end,
        lazy = false,
        init = function() vim.opt.undofile = true end,
        config = function ()
            require('fundo').setup()
        end,}
    },
```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.102233742

I don't know where is wrong,please save my problem

**Comment by serranomorante** [comment]
How do you know is not working? what is the issue?

**Comment by Nestos0** [comment]
I did a test ,just like the vedio in  README,but it does't work,i don't know what happened,my undotree only list Original

**Comment by Nestos0** [comment]
> How do you know is not working? what is the issI did a test ,just like the vedio in README,but it does't work,i don't know what happened,my undotree only list Originalue?



> How do you know is not working? what is the issue?

I did a test ,just like the vedio in README,but it does't work,i don't know what happened,my undotree only list Original

**Comment by kevinhwang91** [comment]
Follow the demo steps and recommended setup.

**Comment by kevinhwang91** [comment]
No idea how to help you.
