### ISSUE TITLE
Does this plugin have any dependencies?

### ISSUE THREAD

**Issue by Nestos0** [kevinhwang91/nvim-fundo#9]
I found that this plugin runs well on my Windows and OpenSUSE Tumbleweed WSL, but it doesn't work on ArchWSL (https://github.com/yuk7/ArchWSL), and it also doesn't run on my physical machine with Arch Linux. What could be the reason?

**Comment by kevinhwang91** [comment]
No, I also use ArchLinux.  Only need `promise-async` and need write permission for `vim.fn.stdpath('cache') .. path.separator .. 'fundo'`

**Comment by Nestos0** [comment]
I think my Arch Linux is jinxed. I tested this plugin in Termux, and it worked like a charm in the Arch Linux container there, as well as in Archwsl. But no matter how many times I've reinstalled it, it just doesn't work on my own Arch Linux

**Comment by NormTurtle** [comment]
@Nestos0 can u try to `ls -lah` of the cache directrory?
see if u have write permisson?

**Comment by Nestos0** [comment]
I discovered the real reason; it's due to the locale. Using Chinese didn't work, but when I switched the localization to English, it started working.
